blog_app:
    resource: "@BlogAppBundle/Controller/"
    type:     annotation
    prefix:   /

blog_admin:
    resource: "@BlogAdminBundle/Controller/"
    type:     annotation
    prefix:   /api

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin