# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sonata.admin.article:
        class: Blog\AdminBundle\Admin\ArticleAdmin
        arguments: [~, Blog\AdminBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Articles", label_catalogue: "BlogAdminBundle" }

    sonata.admin.user:
        class: Blog\AdminBundle\Admin\UserAdmin
        arguments: [~, Blog\AdminBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion", label: "Auteur :", label_catalogue: "BlogAdminBundle" }

    sonata.admin.tag:
        class: Blog\AdminBundle\Admin\TagAdmin
        arguments: [~, Blog\AdminBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion", label: "Tags", label_catalogue: "BlogAdminBundle" }

    sonata.admin.category:
        class: Blog\AdminBundle\Admin\CategoryAdmin
        arguments: [~, Blog\AdminBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion", label: "Categories", label_catalogue: "BlogAdminBundle" }


    kernel.listener.article_listener:
        class: Blog\AdminBundle\Listener\articleListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    kernel.listener.user_listener:
        class: Blog\AdminBundle\Listener\userListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

